language: php

php:
  - 5.6
  - 7.0
  - hhvm

before_script:
  - composer self-update
  - composer --dev install

script:
  - phpunit --coverage-text

notifications:
  email:
    - aferrandini@vocento.com
